config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root to: 'posts#index'
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, length: { maximum: 140,
    too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :posts

  def is_rockstar
    return self.posts.size > 2
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login, except: [:index]


  def index
    @posts = Post.all.reverse
    @new_post = Post.new
  end

  def create
    @temp = Post.create({
      body: params[:post][:body],
      user_id: current_user.id
    })
    if @temp.valid?
      flash[:notice] = "POST CREATED!"
    else
      flash[:notice] = "YOU TYPED TOO MUCH!"
    end
    redirect_to '/'
  end

  # this action shows the form
  def edit
    @post = Post.find(params[:id])
    if current_user.id != @post.user.id
      redirect_to '/'
    end
  end

  #this action handles the form
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    @post.save
  end

  # /post/:id
  def destroy
    @post = Post.find(params[:id])
    if current_user.id == @post.user.id
      @post.destroy
    end
    redirect_to '/'
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chirper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/picnic">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <h1> Chirper </h1>
    <a href="/">
      <%= image_tag  "birb.svg", width: '100px' %>
    </a>
    <br>

    <% if signed_in? %>
      <p>Signed in user: <%= current_user.username %></p>
      <%= button_to 'Sign out', sign_out_path, method: :delete, class: "error" %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path, class: "button" %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <hr>

    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="flex">
  <div></div>
  <div>
    <%= form_for @post  do |f| %>
      <%= f.text_area :body %>

      <br>

      <br>
      <%= f.submit "Update" %>
    <% end %>
  </div>
  <div></div>
</div>

app/views/posts/index.html.erb
<h1>Feed</h1>

<div class="flex">
  <div></div>
  <div>
    <% if current_user %>
      <%= form_for @new_post, html: {class: "something", id: "fizal"} do |f| %>
        <%= f.text_area :body, cols: 20, rows: 10, html: {id: 'create-post'} %>
        <br>
        <%= f.submit "Create" %>
      <% end %>

      <p id="count_message"> </p>
    <% end %>
  </div>
  <div></div>
</div>



<div>
  <% @posts.each do |post| %>
    <p> <%= post.body %> </p>
    <% if current_user %>
      <% if current_user.id == post.user.id %>
        <%= link_to "DELETE", '/posts/' + post.id.to_s, method: :delete, class: "button error" %>
        <%= link_to  "EDIT", edit_post_path(post), class: "button warning" %>
      <% end %>
    <% end %>
    <p> <b> Post by <%= post.user.username %> </b> </p>
    <br>
    <br>
  <% end %>
</div>

app/views/posts/update.html.erb
<h2> POST UPDATED! </h2>
<a href="/">BACK TO HOME</a>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username, type: 'text' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div class="flex">
  <div></div>
  <div>
    <div id="clearance" class="sign-up">
      <h2><%= t(".title") %></h2>

      <%= form_for @user do |form| %>
        <%= render partial: '/users/form', object: form %>

        <div class="submit-field">
          <%= form.submit %>
        </div>

        <div class="other-links">
          <%= link_to t(".sign_in"), sign_in_path %>
        </div>
      <% end %>
    </div>

  </div>
  <div></div>
</div>